"""empty message

Revision ID: 139aa98d505d
Revises: ffdc0a98111c
Create Date: 2021-12-15 09:39:20.405238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139aa98d505d'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
