"""empty message

Revision ID: ce6e54976212
Revises: d2a08565a9c7
Create Date: 2021-12-15 22:55:50.201951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e54976212'
down_revision = 'd2a08565a9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_artists',
    sa.Column('artist_follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['followed_artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('artist_follower_id', 'followed_artist_id')
    )
    op.create_table('users_albums',
    sa.Column('album_follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['followed_album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('album_follower_id', 'followed_album_id')
    )
    op.create_table('users_songs',
    sa.Column('song_follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['song_follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('song_follower_id', 'followed_song_id')
    )
    op.add_column('users', sa.Column('profile_pic', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_table('users_songs')
    op.drop_table('users_albums')
    op.drop_table('users_artists')
    # ### end Alembic commands ###
